import { COMMERCIAL_ROLES } from "../commercial/constants.js";

export const CAPABILITIES = Object.freeze({
  READ_COMMERCIAL: "READ_COMMERCIAL",
  EDIT_RFQ: "EDIT_RFQ",
  CREATE_QUOTE: "CREATE_QUOTE",
  EDIT_COST_BUILD: "EDIT_COST_BUILD",
  REQUEST_APPROVAL: "REQUEST_APPROVAL",
  DECIDE_APPROVAL: "DECIDE_APPROVAL",
  RELEASE_QUOTE: "RELEASE_QUOTE",
  READ_DASHBOARD: "READ_DASHBOARD",
});

export const ROLE_CAPABILITIES = Object.freeze({
  [COMMERCIAL_ROLES.ADMIN]: Object.values(CAPABILITIES),

  [COMMERCIAL_ROLES.MANAGEMENT]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.CREATE_QUOTE,
    CAPABILITIES.EDIT_COST_BUILD,
    CAPABILITIES.REQUEST_APPROVAL,
    CAPABILITIES.DECIDE_APPROVAL,
    CAPABILITIES.RELEASE_QUOTE,
    CAPABILITIES.READ_DASHBOARD,
  ],

  [COMMERCIAL_ROLES.EXPORT]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.EDIT_RFQ,
    CAPABILITIES.CREATE_QUOTE,
    CAPABILITIES.REQUEST_APPROVAL,
    CAPABILITIES.READ_DASHBOARD,
  ],

  [COMMERCIAL_ROLES.MARKET_INTELLIGENCE]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.EDIT_RFQ,
    CAPABILITIES.READ_DASHBOARD,
  ],

  [COMMERCIAL_ROLES.COMMERCIAL]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.CREATE_QUOTE,
    CAPABILITIES.EDIT_COST_BUILD,
    CAPABILITIES.REQUEST_APPROVAL,
    CAPABILITIES.READ_DASHBOARD,
  ],

  [COMMERCIAL_ROLES.FINANCE]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.EDIT_COST_BUILD,
    CAPABILITIES.READ_DASHBOARD,
  ],

  [COMMERCIAL_ROLES.RISK_REVIEWER]: [
    CAPABILITIES.READ_COMMERCIAL,
    CAPABILITIES.EDIT_RFQ,
    CAPABILITIES.READ_DASHBOARD,
  ],
});
